# Generated by Django 3.0.5 on 2021-02-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210224_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
